### ISSUE TITLE
Define DID Document class in accordance with DID/DDO specifications 

### ISSUE THREAD

**Issue by katszwn** [jolocom/jolocom-lib#1]
## Description
It should contain:
- `@context` - the version of DID specifications
- `id` unique identifier with colon separated description, ex. `did:jol:2829fen32992jkjdk2o3`
- `authenticationCredential` a separate class, describing public key that is used by the owner 
- `signature` a JSON-LD compatible signature, example [here](https://w3c-dvcg.github.io/ld-signatures/)
- `created` timestamp of identity creation

## TODO
- [x] Add DidDocument class
- [x] Add AuthorizatioCredential class
- [x] de- and serialization of AuthorizationCredential class
- [x] de- and serialization of DidDocument class

**Comment by Exulansis** [comment]
Is this finished @charleenfei @katszwn?

**Comment by katszwn** [comment]
No, however the general structure is pushed to the corresponding branch.
JSON formatting and the rest of the tests is in progress.

W dniu wt., 23.01.2018 o 16:56 Eugeniu Rusu <notifications@github.com>
napisał(a):

**Comment by Exulansis** [comment]
Understood, one thing we might consider is treating the document as JSON-LD, for that what it is, rather than simply editing it as a simple JSON document. Not sure if there is much value in it though for the underlying graph is fairly basic.
Will look into this in more detail.

**Comment by katszwn** [comment]
@Exulansis so the whole DID/DDO specification conforms to JSON-LD format. Which is cool, because we can use https://github.com/digitalbazaar/jsonld.js :)
