### ISSUE TITLE
Implement Identity Class as member of IdentityWallet

### ISSUE THREAD

**Issue by nataschaberg** [jolocom/jolocom-lib#108]
### Description
implement get public profile on Identity class which is a member on IdentityWallet

### TODO
- [x] implement Identity class which extends DidDocument
- [x] implement identity.publicProfile.get on class
- [x] implement test for Identity class
