### ISSUE TITLE
JolocomRegistry update commit and resolve functionality 

### ISSUE THREAD

**Issue by nataschaberg** [jolocom/jolocom-lib#111]
### Description
1) commit  method should account for both update and create
2) resolve method needs to resolve DidDocument and PublicProfile claim and return Identity class

### TODO
- [x] add check for DidDocument & remove pin in case it is there 
- [x] resolve DidDocument and the PublicProfile claim
- [x] add/expand tests
