### ISSUE TITLE
Review the documentation and update with more details

### ISSUE THREAD

**Issue by katszwn** [jolocom/jolocom-lib#144]
### Description
Review the Getting started section of the documentation and add details. 

### TODO
- [x] add info about the fueling service
- [x] link to connectors
- [x] add details about key derivation
- [x] add return type of key derivation
