### ISSUE TITLE
Add proof to DID document and create it from the private key

### ISSUE THREAD

**Issue by katszwn** [jolocom/jolocom-lib#147]
### Description
A DDO should contain a `proof` section. So it needs to be created with a private key instead of a public one.

### TODO
- [ ] change the creation method to be `fromPrivateKey`
- [ ] add a `proof` section to DDO
- [ ] populate `proof` on creation

**Comment by katszwn** [comment]
Closed in https://github.com/jolocom/jolocom-lib/pull/156
