### ISSUE TITLE
Fixes around the public profile

### ISSUE THREAD

**Issue by katszwn** [jolocom/jolocom-lib#148]
### TODO
- [x] make `services` section optional 
- [ ] commit public profile in the `commit` method
- [ ] add a setter for public profile on the DDO 
- [ ] make a profile public on Identity
- [x] on `resolve` filter for Jolocom public profile Credential instead of mapping through all service endpoints
- [ ] add an entry for public profile to our default context
