### ISSUE TITLE
Incorporate SSO Flow into integration test

### ISSUE THREAD

**Issue by charleenfei** [jolocom/jolocom-lib#184]
### Description

Currently, the integration test only covers Identity creation and registration. We should extend the test to cover the SSO interaction flow.

### TODO
- [x] yarn command to run integration test
- [x] CredentialRequest
- [x] credential creation (payload)
- [x] CredentialResponse with appropriate payload

**Comment by charleenfei** [comment]
addressed by PR #192
