### ISSUE TITLE
Set up CLI interface

### ISSUE THREAD

**Issue by charleenfei** [jolocom/jolocom-lib#20]
### Description

We should set up a CLI interface for interaction with the Jolocom Library

### TODO:

Enable users to:

- [ ] Generate and retrieve a DID/DDO
- [ ] Generate and retrieve associated keys
- [ ] Additional functionalities TBD
