### ISSUE TITLE
Enable passing a registry whenever it's used internally

### ISSUE THREAD

**Issue by katszwn** [jolocom/jolocom-lib#206]
### Description
The concept of `Registry` is  there to enable interoperability. Currently we have some methods which use the registry under the hood, but we can't pass it in - that destroys the interoperability part. 

We need to enable optional passing in custom registry whenever we use it internally - it should still use the default registry in the case when no custom registry is provided. 

### TODO
- [ ] [JSONWebToken decode method](https://github.com/jolocom/jolocom-lib/blob/master/ts/interactionFlows/JSONWebToken.ts#L58)
- [ ] check if there are any other methods where we don't enable passing in custom registry
- [ ] remove stubs in the integration test

**Comment by nataschaberg** [comment]
This issue was fixed by #232
