### ISSUE TITLE
Create and update public verifiable credentials

### ISSUE THREAD

**Issue by charleenfei** [jolocom/jolocom-lib#23]
### Description

The library should expose methods to create, sign, and verify claims about the identity.

### TODO:

- [x] Define verifiable credential structure.
- JWT v. JSON-LD: JWT is neater with less convoluted (and/or irrelevant) syntax. But, JWT is a base64 encoded blob -- you can't see the content unless you decode it, which is potentially a problem or limitation for potential [searchable public credentials](https://github.com/ipfs-search/ipfs-search)
- Consider JWT for 'private' claims (ES256 alg in header for asymmetric decoding) and JSON-LD for public?
- JSON-LD VC structure would follow the W3C Verifiable Claims standard, and use a [W3C signature suite](https://github.com/digitalbazaar/jsonld-signatures) for a LD signature.
- Which one could best be expanded to handle multisig situations? uPort goes with array of JWT to represent multi-sig. Possibility: set IPFS claim hashes into IPLD as [merkle-dags](https://github.com/ipld/js-ipld-graph-builder) for multisig?
- [ ] Refactor DID class to include method for creating, signing, and verifying verifiable credential.
- typechecking in method for valid DID?
- [x] Add DID interface
