### ISSUE TITLE
Include Authentication in the library interface

### ISSUE THREAD

**Issue by katszwn** [jolocom/jolocom-lib#28]
### Description
Expose Authentication module in the library

### TODO
- [x] create a class Authentication that encapsulates all needed functionalities
- [x] create authentication config 
- [x] include Authentication in Jolocom lib
