### ISSUE TITLE
Include Claims in the library interface

### ISSUE THREAD

**Issue by katszwn** [jolocom/jolocom-lib#31]
### Description
Add Vierifiable Claims to the library interface

### TODO
- [ ] Resolve TS Buffer issue `TS2345: Argument of type 'SharedArrayBuffer | ArrayBuffer' is not assignable to parameter of type 'string'. Type 'SharedArrayBuffer' is not assignable to type 'string'`
- [ ] Create a class encapsulating claims creating and verification
- [ ] Include the new module in JolocomLib
