### ISSUE TITLE
Implement support for IPFS Pub Subs

### ISSUE THREAD

**Issue by Exulansis** [jolocom/jolocom-lib#34]
### Description

The library should be able to connect to public gateways exposing pub sub related api endpoints for purposes of SSO and claim exchange.

### TODO
- [ ] Implement the functionality
- Currently, the PubSub API only works in Node.js enviroment.
- [ ] Implement corresponding tests
- [ ] Provide relevant documentation.
