### ISSUE TITLE
Use commitizen and semantic-release

### ISSUE THREAD

**Issue by mnzaki** [jolocom/jolocom-lib#348]
### Description
[semantic-release](https://www.npmjs.com/package/semantic-release) can create a changelog and decide on the version number automatically if we just stick to properly formatted commit messages, which we can also easily do with [commitizen](https://github.com/commitizen/cz-cli)

### TODO
- [ ] Add and configure commitizen
- [ ] Add notes/docs/links to expected commit message format
- [ ] Add and configure semantic-release
