### ISSUE TITLE
Architectural Nuisance 1

### ISSUE THREAD

**Issue by mnzaki** [jolocom/jolocom-lib#355]
### Description
First the easy and relatively clear bits.

### TODO
- [ ] Export classes directly from `index.ts`
- [ ] Keep constructor work inside constructors
- [ ] Decouple `identityWallet` from `registry`
  - [ ] Consolidate validation logic into one place 
  - [ ] Create new payment interface to decouple `sendTransaction` from `identityWallet`
