### ISSUE TITLE
Support user defined expiration dates

### ISSUE THREAD

**Issue by Exulansis** [jolocom/jolocom-lib#369]
### Description
Add support for passing custom expiry dates when creating *Signed Credentials* and *Interaction Tokens*.

Currently the lib fills in the values automatically (to 1 year for Credentials, and 1 hour for Interaction tokens).

### TODO
- [x] Allow library users to pass the expiry date as part of Credential / Token creation flow.
- [x] Add unit tests to ensure the values are set correctly.
- [ ] Document the new API.
