### ISSUE TITLE
Define sane default contexts for JSONLD documents.

### ISSUE THREAD

**Issue by Exulansis** [jolocom/jolocom-lib#52]
### Description

In order to have reliable signatures, the JSONLD documents needs to be canonized / normalized before being passed to a digest function. The canonization step includes expanding / mapping the keys in the document to corresponding predicates. If the context is incomplete, some keys might map incorrectly (e.g. to a member of the schema.org vocabulary instead of the security / identity vocabularies).

### TODO
- [x] Define a list of default contexts that allow for reliable normalization.
- [x] Extend the list for predicates introduced in custom claims (e.g.) email.
- [x] Store local versions of the vocabularies to avoid having to perform network requests during the normalization phase.
- [x] Ensure that the canonization still occurs correctly.

**Comment by Exulansis** [comment]
Done.
