### ISSUE TITLE
Modify credential types

### ISSUE THREAD

**Issue by Exulansis** [jolocom/jolocom-lib#66]
### Description

Currently all credentials are types as `Credential`, in order to be spec compliant, and more explicit, we should use a more specific type, for instance `['Credential', 'ProofOfEmailCredential']`.

### TODO
- [x] Include these types in the credential structure
- [x] Ensure they are resolved during the normalization phase
- [x] Include the new types in the `claimsMetadata` object
