### ISSUE TITLE
Refactor functionality around generating HD keys to IdentityManager 

### ISSUE THREAD

**Issue by katszwn** [jolocom/jolocom-lib#83]
### Description
Create a module of the Library that takes care of deriving HD keys according to different paths.

### TODO
- [ ] define a static `create` method which takes `seed`
- [ ] define an enum for key types
- [ ] define a member of the class - key derivation `derivationSchema` (?), which is a mapping between name and the path (`[key: string] : string`) with the basic key types
- [ ] define `getSchema()`
- [ ] define `deriveMnemonic` method, which returns mnemonic for a seed
- [ ] define `deriveKey`, which takes `name` and derives a key with a corresponding path taken from schema
- [ ] add placeholder for a method to add an entry to schema (for a custom key)
