### ISSUE TITLE
Implement IPLD for public verifiable credentials storage

### ISSUE THREAD

**Issue by charleenfei** [jolocom/jolocom-lib#88]
### Description

This task should implement the infrastructure needed to have a public credentials storage/service endpoint on the DDO.

IPLD will be used for easier routing to specific claims (tentatively, by claim ID).

### TODO
- [x] create DAG object from claim
- [ ] Public profile in data field of initial DAG object?
- [x] create DAG links between claims
- [x] methods to route to specific claims by claimID
- [ ] unit testing
