### ISSUE TITLE
Make the reviving related methods static.

### ISSUE THREAD

**Issue by Exulansis** [jolocom/jolocom-lib#89]
### Description

Currently reviving a instances from  JSON / JWTs looks as follows:
```javascript
const vCred = new VerifiableCredential().fromJSON(json)
const CR = new CredentialRequest().fromJWT(jwt)
```

It should be changed to function as follows:
```javascript
const vCred = VerifiableCredential.fromJSON()
const CR = CredentialRequest.fromJSON()
```

This will allow for the implementation of #85 to be more idiomatic.

### TODO
- [x] Update credential class
- [x] Update verifiable credential class
- [x] Update credentialRequest / credentialResponse classes.
