### ISSUE TITLE
Encapsulate creating and signing entities in an IdentityWallet

### ISSUE THREAD

**Issue by katszwn** [jolocom/jolocom-lib#97]
### Description
Move all the functionality that needs access to identity private key to a new class - `IdentityWallet` 

### TODO
- [x] create a class with private key and ddo as members
- [x] add a static `create` method for the `IdentityWallet`
- [x] add setters and getters for ddo
- [x] add entities' `create` methods
- [ ] add `sign` methods
