### ISSUE TITLE
Public Profile

### ISSUE THREAD

**Issue by charleenfei** [jolocom/jolocom-lib#99]
### Description

Implement a public profile in the serviceEndpoint section of the DDO.

### TODO
- [ ] JSON-LD PublicProfile, IPFS file
- [x] check available predicates on schema.org
- [ ] check keyword 'link' on IPLD
- [x] check resolution of arrays on IPLD
